/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdvancedShipmentOptionsDangerousGoodsContact } from './advanced-shipment-options-dangerous-goods-contact';
import { AdvancedShipmentOptionsDryIceWeight } from './advanced-shipment-options-dry-ice-weight';
import { AdvancedShipmentOptionsFedexFreight } from './advanced-shipment-options-fedex-freight';
import { BillToParty } from './bill-to-party';
import { CollectOnDelivery } from './collect-on-delivery';
import { OriginType } from './origin-type';

/**
 * Advanced shipment options
 * @export
 * @interface AdvancedShipmentOptions
 */
export interface AdvancedShipmentOptions {
    /**
     * This field is used to [bill shipping costs to a third party](https://www.shipengine.com/docs/shipping/bill-to-third-party/).  This field must be used in conjunction with the `bill_to_country_code`, `bill_to_party`, and `bill_to_postal_code` fields. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'bill_to_account'?: string | null;
    /**
     * The two-letter [ISO 3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the third-party that is responsible for shipping costs. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'bill_to_country_code'?: string | null;
    /**
     * Indicates whether to bill shipping costs to the recipient or to a third-party.  When billing to a third-party, the `bill_to_account`, `bill_to_country_code`, and `bill_to_postal_code` fields must also be set. 
     * @type {BillToParty}
     * @memberof AdvancedShipmentOptions
     */
    'bill_to_party'?: BillToParty | null;
    /**
     * The postal code of the third-party that is responsible for shipping costs. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'bill_to_postal_code'?: string | null;
    /**
     * Indicates that the shipment contains alcohol.
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'contains_alcohol'?: boolean;
    /**
     * Indicates that the shipper is paying the international delivery duties for this shipment.  This option is supported by UPS, FedEx, and DHL Express. 
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'delivered_duty_paid'?: boolean;
    /**
     * Indicates if the shipment contain dry ice
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'dry_ice'?: boolean;
    /**
     * 
     * @type {AdvancedShipmentOptionsDryIceWeight}
     * @memberof AdvancedShipmentOptions
     */
    'dry_ice_weight'?: AdvancedShipmentOptionsDryIceWeight | null;
    /**
     * Indicates that the package cannot be processed automatically because it is too large or irregularly shaped. This is primarily for USPS shipments.  See [Section 1.2 of the USPS parcel standards](https://pe.usps.com/text/dmm300/101.htm#ep1047495) for details. 
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'non_machinable'?: boolean;
    /**
     * Enables Saturday delivery, if supported by the carrier.
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'saturday_delivery'?: boolean;
    /**
     * 
     * @type {AdvancedShipmentOptionsFedexFreight}
     * @memberof AdvancedShipmentOptions
     */
    'fedex_freight'?: AdvancedShipmentOptionsFedexFreight;
    /**
     * Whether to use [UPS Ground Freight pricing](https://www.shipengine.com/docs/shipping/ups-ground-freight/).  If enabled, then a `freight_class` must also be specified. 
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'use_ups_ground_freight_pricing'?: boolean | null;
    /**
     * The National Motor Freight Traffic Association [freight class](http://www.nmfta.org/pages/nmfc?AspxAutoDetectCookieSupport=1), such as \"77.5\", \"110\", or \"250\". 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'freight_class'?: string | null;
    /**
     * An arbitrary field that can be used to store information about the shipment. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'custom_field1'?: string | null;
    /**
     * An arbitrary field that can be used to store information about the shipment. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'custom_field2'?: string | null;
    /**
     * An arbitrary field that can be used to store information about the shipment. 
     * @type {string}
     * @memberof AdvancedShipmentOptions
     */
    'custom_field3'?: string | null;
    /**
     * 
     * @type {OriginType}
     * @memberof AdvancedShipmentOptions
     */
    'origin_type'?: OriginType | null;
    /**
     * Indicate to the carrier that this shipment requires additional handling. 
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'additional_handling'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'shipper_release'?: boolean | null;
    /**
     * 
     * @type {CollectOnDelivery}
     * @memberof AdvancedShipmentOptions
     */
    'collect_on_delivery'?: CollectOnDelivery;
    /**
     * Third Party Consignee option is a value-added service that allows the shipper to supply goods without commercial invoices being attached
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'third_party_consignee'?: boolean;
    /**
     * Indicates if the Dangerous goods are present in the shipment
     * @type {boolean}
     * @memberof AdvancedShipmentOptions
     */
    'dangerous_goods'?: boolean;
    /**
     * 
     * @type {AdvancedShipmentOptionsDangerousGoodsContact}
     * @memberof AdvancedShipmentOptions
     */
    'dangerous_goods_contact'?: AdvancedShipmentOptionsDangerousGoodsContact;
}

