/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A Fedex account information request body
 * @export
 * @interface ConnectFedexRequestBody
 */
export interface ConnectFedexRequestBody {
    /**
     * Account number
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'account_number': string;
    /**
     * Address
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'address1': string;
    /**
     * Address
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'address2'?: string;
    /**
     * The city
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'city': string;
    /**
     * The company
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'company'?: string;
    /**
     * Country code
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'country_code': string;
    /**
     * An email address.
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'email': string;
    /**
     * First name
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'first_name': string;
    /**
     * Last name
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'last_name': string;
    /**
     * Phone number
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'phone': string;
    /**
     * Postal Code
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'postal_code': string;
    /**
     * State
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'state': string;
    /**
     * Nickname
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'nickname': string;
    /**
     * Boolean signaling agreement to the Fedex End User License Agreement
     * @type {boolean}
     * @memberof ConnectFedexRequestBody
     */
    'agree_to_eula': boolean;
    /**
     * Meter number
     * @type {string}
     * @memberof ConnectFedexRequestBody
     */
    'meter_number'?: string;
}

