/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdvancedShipmentOptions } from './advanced-shipment-options';
import { DeliveryConfirmation } from './delivery-confirmation';
import { InsuranceProvider } from './insurance-provider';
import { OrderSourceName } from './order-source-name';
import { Package } from './package';
import { PartialShipmentCustoms } from './partial-shipment-customs';
import { ShipmentItem } from './shipment-item';
import { ShipmentStatus } from './shipment-status';
import { ShippingAddress } from './shipping-address';
import { ShippingAddressTo } from './shipping-address-to';
import { Tag } from './tag';
import { TaxIdentifier } from './tax-identifier';
import { Weight } from './weight';

/**
 * The information necessary to ship a package, such as the origin, the destination, the carrier service, and the package dimensions and weight. 
 * @export
 * @interface PartialShipment
 */
export interface PartialShipment {
    /**
     * Arbitrary tags associated with this shipment.  Tags can be used to categorize shipments, and shipments can be queried by their tags. 
     * @type {Array<Tag>}
     * @memberof PartialShipment
     */
    'tags'?: Array<Tag>;
    /**
     * A string that uniquely identifies a ShipEngine resource, such as a carrier, label, shipment, etc.
     * @type {string}
     * @memberof PartialShipment
     */
    'shipment_id'?: string;
    /**
     * A string that uniquely identifies a ShipEngine resource, such as a carrier, label, shipment, etc.
     * @type {string}
     * @memberof PartialShipment
     */
    'carrier_id'?: string;
    /**
     * A [carrier service](https://www.shipengine.com/docs/shipping/use-a-carrier-service/), such as `fedex_ground`, `usps_first_class_mail`, `flat_rate_envelope`, etc. 
     * @type {string}
     * @memberof PartialShipment
     */
    'service_code'?: string;
    /**
     * ID that the Order Source assigned
     * @type {string}
     * @memberof PartialShipment
     */
    'external_order_id'?: string | null;
    /**
     * Describe the packages included in this shipment as related to potential metadata that was imported from external order sources 
     * @type {Array<ShipmentItem>}
     * @memberof PartialShipment
     */
    'items'?: Array<ShipmentItem>;
    /**
     * 
     * @type {Array<TaxIdentifier>}
     * @memberof PartialShipment
     */
    'tax_identifiers'?: Array<TaxIdentifier> | null;
    /**
     * A unique user-defined key to identify a shipment.  This can be used to retrieve the shipment.  > **Warning:** The `external_shipment_id` is limited to 50 characters. Any additional characters will be truncated. 
     * @type {string}
     * @memberof PartialShipment
     */
    'external_shipment_id'?: string | null;
    /**
     * A non-unique user-defined number used to identify a shipment.  If undefined, this will match the external_shipment_id of the shipment.  > **Warning:** The `shipment_number` is limited to 50 characters. Any additional characters will be truncated. 
     * @type {string}
     * @memberof PartialShipment
     */
    'shipment_number'?: string | null;
    /**
     * An [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string that represents a date, but not a specific time.  The value _may_ contain a time component, but it will be set to `00:00:00` UTC by ShipEngine. 
     * @type {string}
     * @memberof PartialShipment
     */
    'ship_date'?: string;
    /**
     * An [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string that represents a date and time. 
     * @type {string}
     * @memberof PartialShipment
     */
    'created_at'?: string;
    /**
     * An [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string that represents a date and time. 
     * @type {string}
     * @memberof PartialShipment
     */
    'modified_at'?: string;
    /**
     * The current status of the shipment
     * @type {ShipmentStatus}
     * @memberof PartialShipment
     */
    'shipment_status'?: ShipmentStatus;
    /**
     * The recipient\'s mailing address
     * @type {ShippingAddressTo}
     * @memberof PartialShipment
     */
    'ship_to'?: ShippingAddressTo;
    /**
     * The shipment\'s origin address. If you frequently ship from the same location, consider [creating a warehouse](https://www.shipengine.com/docs/reference/create-warehouse/).  Then you can simply specify the `warehouse_id` rather than the complete address each time. 
     * @type {ShippingAddress}
     * @memberof PartialShipment
     */
    'ship_from'?: ShippingAddress;
    /**
     * The [warehouse](https://www.shipengine.com/docs/shipping/ship-from-a-warehouse/) that the shipment is being shipped from.  Either `warehouse_id` or `ship_from` must be specified. 
     * @type {string}
     * @memberof PartialShipment
     */
    'warehouse_id'?: string | null;
    /**
     * The return address for this shipment.  Defaults to the `ship_from` address. 
     * @type {ShippingAddress}
     * @memberof PartialShipment
     */
    'return_to'?: ShippingAddress;
    /**
     * An optional indicator if the shipment is intended to be a return. Defaults to false if not provided. 
     * @type {boolean}
     * @memberof PartialShipment
     */
    'is_return'?: boolean | null;
    /**
     * The type of delivery confirmation that is required for this shipment.
     * @type {DeliveryConfirmation}
     * @memberof PartialShipment
     */
    'confirmation'?: DeliveryConfirmation;
    /**
     * 
     * @type {PartialShipmentCustoms}
     * @memberof PartialShipment
     */
    'customs'?: PartialShipmentCustoms | null;
    /**
     * Advanced shipment options.  These are entirely optional.
     * @type {AdvancedShipmentOptions}
     * @memberof PartialShipment
     */
    'advanced_options'?: AdvancedShipmentOptions;
    /**
     * The insurance provider to use for any insured packages in the shipment. 
     * @type {InsuranceProvider}
     * @memberof PartialShipment
     */
    'insurance_provider'?: InsuranceProvider;
    /**
     * The order sources that are supported by ShipEngine
     * @type {OrderSourceName}
     * @memberof PartialShipment
     */
    'order_source_code'?: OrderSourceName;
    /**
     * The packages in the shipment.  > **Note:** Some carriers only allow one package per shipment.  If you attempt to create a multi-package shipment for a carrier that doesn\'t allow it, an error will be returned. 
     * @type {Array<Package>}
     * @memberof PartialShipment
     */
    'packages'?: Array<Package>;
    /**
     * The combined weight of all packages in the shipment
     * @type {Weight}
     * @memberof PartialShipment
     */
    'total_weight'?: Weight;
    /**
     * Calculate a rate for this shipment with the requested carrier using a ratecard that differs from the default.  Only supported for UPS and USPS.
     * @type {string}
     * @memberof PartialShipment
     */
    'comparison_rate_type'?: string | null;
}

