/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MonetaryValue } from './monetary-value';
import { RateType } from './rate-type';
import { ValidationStatus } from './validation-status';

/**
 * A rate estimate
 * @export
 * @interface RateEstimate
 */
export interface RateEstimate {
    /**
     * The possible rate type values
     * @type {RateType}
     * @memberof RateEstimate
     */
    'rate_type': RateType;
    /**
     * A string that uniquely identifies a ShipEngine resource, such as a carrier, label, shipment, etc.
     * @type {string}
     * @memberof RateEstimate
     */
    'carrier_id': string;
    /**
     * The shipping amount
     * @type {MonetaryValue}
     * @memberof RateEstimate
     */
    'shipping_amount': MonetaryValue;
    /**
     * The insurance amount
     * @type {MonetaryValue}
     * @memberof RateEstimate
     */
    'insurance_amount': MonetaryValue;
    /**
     * The confirmation amount
     * @type {MonetaryValue}
     * @memberof RateEstimate
     */
    'confirmation_amount': MonetaryValue;
    /**
     * Any other charges associated with this rate
     * @type {MonetaryValue}
     * @memberof RateEstimate
     */
    'other_amount': MonetaryValue;
    /**
     * Tariff and additional taxes associated with an international shipment.
     * @type {MonetaryValue}
     * @memberof RateEstimate
     */
    'tax_amount'?: MonetaryValue;
    /**
     * Certain carriers base [their rates](https://blog.stamps.com/2017/09/08/usps-postal-zones/) off of custom zones that vary depending upon the ship_to and ship_from location 
     * @type {number}
     * @memberof RateEstimate
     */
    'zone': number | null;
    /**
     * package type that this rate was estimated for
     * @type {string}
     * @memberof RateEstimate
     */
    'package_type': string | null;
    /**
     * The number of days estimated for delivery, this will show the _actual_ delivery time if for example, the package gets shipped on a Friday 
     * @type {number}
     * @memberof RateEstimate
     */
    'delivery_days'?: number;
    /**
     * Indicates if the rate is guaranteed.
     * @type {boolean}
     * @memberof RateEstimate
     */
    'guaranteed_service': boolean;
    /**
     * An [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string that represents a date, but not a specific time.  The value _may_ contain a time component, but it will be set to `00:00:00` UTC by ShipEngine. 
     * @type {string}
     * @memberof RateEstimate
     */
    'estimated_delivery_date'?: string;
    /**
     * The carrier delivery days
     * @type {string}
     * @memberof RateEstimate
     */
    'carrier_delivery_days'?: string;
    /**
     * ship date
     * @type {string}
     * @memberof RateEstimate
     */
    'ship_date'?: string;
    /**
     * Indicates if the rates been negotiated
     * @type {boolean}
     * @memberof RateEstimate
     */
    'negotiated_rate': boolean;
    /**
     * service type
     * @type {string}
     * @memberof RateEstimate
     */
    'service_type': string;
    /**
     * service code for the rate
     * @type {string}
     * @memberof RateEstimate
     */
    'service_code': string;
    /**
     * Indicates if rate is trackable
     * @type {boolean}
     * @memberof RateEstimate
     */
    'trackable': boolean;
    /**
     * A [shipping carrier](https://www.shipengine.com/docs/carriers/setup/), such as `fedex`, `dhl_express`, `stamps_com`, etc.
     * @type {string}
     * @memberof RateEstimate
     */
    'carrier_code': string;
    /**
     * carrier nickname
     * @type {string}
     * @memberof RateEstimate
     */
    'carrier_nickname': string;
    /**
     * carrier friendly name
     * @type {string}
     * @memberof RateEstimate
     */
    'carrier_friendly_name': string;
    /**
     * The possible validation status values
     * @type {ValidationStatus}
     * @memberof RateEstimate
     */
    'validation_status': ValidationStatus;
    /**
     * The warning messages
     * @type {Array<string>}
     * @memberof RateEstimate
     */
    'warning_messages': Array<string>;
    /**
     * The error messages
     * @type {Array<string>}
     * @memberof RateEstimate
     */
    'error_messages': Array<string>;
}

