/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IdentifierType } from './identifier-type';
import { TaxableEntityType } from './taxable-entity-type';

/**
 * A tax identifier object
 * @export
 * @interface TaxIdentifier
 */
export interface TaxIdentifier {
    /**
     * The taxable entity type for this tax item. Valid values include the following  |Value       |Description |:---------  |:----------------------------------------------------- |`shipper`   | The shipper is responsible for this tax. |`recipient` | The recipient of the shipment is responsible for this tax. |`ior`       | The importer of records is responsible for tax. 
     * @type {TaxableEntityType}
     * @memberof TaxIdentifier
     */
    'taxable_entity_type': TaxableEntityType;
    /**
     * Tax identifier type for customs declaration  |Pickup Type    | Description |---------------|----------------------------------------- |`vat`          | The tax identifier is a Value Added Tax. |`eori`         | The tax identifier is an Economic Operators Registration and Identification Number (EORI). |`ssn`          | The tax identifier is a Social Security Number. |`ein`          | The tax identifier is an Employer Identification Number (EIN). |`tin`          | The tax identifier is a Tax Identification Number (TIN). |`ioss`         | The tax identifier is an Import One-Stop Shop (IOSS). |`pan`          | The tax identifier is a Permanent Account Number (PAN). |`voec`         | The tax identifier is a Norwegian VAT On E-Commerce(VOEC). |`pccc`         | The tax identifier is a Personal Customs Clearance Code (PCCC). |`oss`          | The tax identifier is an One-Stop Shop (OSS). |`passport`     | The tax identifier is a Passport Number. |`abn`          | The tax identifier is an Australian Business Number. 
     * @type {IdentifierType}
     * @memberof TaxIdentifier
     */
    'identifier_type': IdentifierType;
    /**
     * The authority that issued this tax. This must be a valid 2 character ISO 3166 Alpha 2 country code.
     * @type {string}
     * @memberof TaxIdentifier
     */
    'issuing_authority': string;
    /**
     * The value of the identifier
     * @type {string}
     * @memberof TaxIdentifier
     */
    'value': string;
}

