/*
ShipEngine API

ShipEngine's easy-to-use REST API lets you manage all of your shipping needs without worrying about the complexities of different carrier APIs and protocols. We handle all the heavy lifting so you can focus on providing a first-class shipping experience for your customers at the best possible prices.

Each of ShipEngine's features can be used by itself or in conjunction with each other to build powerful shipping functionality into your application or service.

## Getting Started
If you're new to REST APIs then be sure to read our [introduction to REST](https://www.shipengine.com/docs/rest/) to understand the basics.  Learn how to [authenticate yourself to ShipEngine](https://www.shipengine.com/docs/auth/), and then use our [sandbox environment](https://www.shipengine.com/docs/sandbox/) to kick the tires and get familiar with our API. If you run into any problems, then be sure to check the [error handling guide](https://www.shipengine.com/docs/errors/) for tips.

Here are some step-by-step **tutorials** to get you started:

  - [Learn how to create your first shipping label](https://www.shipengine.com/docs/labels/create-a-label/)
  - [Calculate shipping costs and compare rates across carriers](https://www.shipengine.com/docs/rates/)
  - [Track packages on-demand or in real time](https://www.shipengine.com/docs/tracking/)
  - [Validate mailing addresses anywhere on Earth](https://www.shipengine.com/docs/addresses/validation/)


## Shipping Labels for Every Major Carrier
ShipEngine makes it easy to [create shipping labels for any carrier](https://www.shipengine.com/docs/labels/create-a-label/) and [download them](https://www.shipengine.com/docs/labels/downloading/) in a [variety of file formats](https://www.shipengine.com/docs/labels/formats/). You can even customize labels with your own [messages](https://www.shipengine.com/docs/labels/messages/) and [images](https://www.shipengine.com/docs/labels/branding/).


## Real-Time Package Tracking
With ShipEngine you can [get the current status of a package](https://www.shipengine.com/docs/tracking/) or [subscribe to real-time tracking updates](https://www.shipengine.com/docs/tracking/webhooks/) via webhooks. You can also create [custimized tracking pages](https://www.shipengine.com/docs/tracking/branded-tracking-page/) with your own branding so your customers will always know where their package is.


## Compare Shipping Costs Across Carriers
Make sure you ship as cost-effectively as possible by [comparing rates across carriers](https://www.shipengine.com/docs/rates/get-shipment-rates/) using the ShipEngine Rates API. Or if you don't know the full shipment details yet, then you can [get rate estimates](https://www.shipengine.com/docs/rates/estimate/) with limited address info.


## Worldwide Address Validation
ShipEngine supports [address validation](https://www.shipengine.com/docs/addresses/validation/) for virtually [every country on Earth](https://www.shipengine.com/docs/addresses/validation/countries/), including the United States, Canada, Great Britain, Australia, Germany, France, Norway, Spain, Sweden, Israel, Italy, and over 160 others.


The version of the OpenAPI document: 1.1.202403202303
Contact: sales@shipengine.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AncillaryServiceEndorsement } from './ancillary-service-endorsement';
import { UpsInvoice } from './ups-invoice';
import { UpsPickupType } from './ups-pickup-type';

/**
 * UPS account settings
 * @export
 * @interface UpsAccountSettings
 */
export interface UpsAccountSettings {
    /**
     * nickname
     * @type {string}
     * @memberof UpsAccountSettings
     */
    'nickname'?: string;
    /**
     * Indicates if this is the primary UPS account
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'is_primary_account'?: boolean;
    /**
     * The possible ups pickup type values
     * @type {UpsPickupType}
     * @memberof UpsAccountSettings
     */
    'pickup_type'?: UpsPickupType;
    /**
     * The use carbon neutral shipping program
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'use_carbon_neutral_shipping_program'?: boolean;
    /**
     * The use ground freight pricing
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'use_ground_freight_pricing'?: boolean;
    /**
     * The use consolidation services
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'use_consolidation_services'?: boolean;
    /**
     * The use order number on mail innovations labels
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'use_order_number_on_mail_innovations_labels'?: boolean;
    /**
     * [Ancillary service endorsements](https://pe.usps.com/text/qsg300/Q507.htm) are used by mailers to request an addressee\'s new address and to provide the carrier with instructions on how to handle packages that are undeliverable as addressed.  | Ancillary Service Endorsement  | Description |--------------------------------|----------------------------------------------------- | `none`                         | No ancillary service is requested. Depending on the carrier servive, the package may be forwarded, returned, or discarded. | `return_service_requested`     | The package is returned to the sender. If possible, notification of the new address is is included with the returned package. | `forwarding_service_requested` | Forward the package to the new address, if possible; otherwise, return it to the sender. | `address_service_requested`    | Forward the package to the new address, if possible; otherwise, return it to the sender. This is similar to `forwarding_service_requested`, but different restrictions and charges may apply. | `change_service_requested`     | The package is discarded. If possible, notification of the new address is sent to the sender. | `leave_if_no_response`         | 
     * @type {AncillaryServiceEndorsement}
     * @memberof UpsAccountSettings
     */
    'mail_innovations_endorsement'?: AncillaryServiceEndorsement;
    /**
     * mail innovations cost center
     * @type {string}
     * @memberof UpsAccountSettings
     */
    'mail_innovations_cost_center'?: string;
    /**
     * The use negotiated rates
     * @type {boolean}
     * @memberof UpsAccountSettings
     */
    'use_negotiated_rates'?: boolean;
    /**
     * account postal code
     * @type {string}
     * @memberof UpsAccountSettings
     */
    'account_postal_code'?: string;
    /**
     * The invoice
     * @type {UpsInvoice}
     * @memberof UpsAccountSettings
     */
    'invoice'?: UpsInvoice;
}

